language: node_js
node_js:
- 5.5.0
# cache:
#   yarn: true
#   directories:
#     - node_modules

script:
- "apt-get install -y ccrypt"
- echo keys are here > tfile
- echo AWS_KEY = $AWS_KEY >>tfile
- echo AWS_SECRET = $AWS_SECRET >>tfile
- echo QA_AWS_KEY = $QA_AWS_KEY >>tfile
- echo QA_AWS_SECRET = $QA_AWS_SECRET >>tfile
- echo MASTER_AWS_KEY = $MASTER_AWS_KEY >>tfile
- echo MASTER_AWS_SECRET = $MASTER_AWS_SECRET >>tfile
- echo TEST_AWS_KEY = $TEST_AWS_KEY >>tfile
- echo TEST_AWS_SECRET = $TEST_AWS_SECRET >>tfile
- npm cache clean
- npm run lint && npm test && npm run build
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
deploy:
- provider: s3
  cache_control: private, no-store, no-cache, must-revalidate, max-age=0
  detect_encoding: true
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: connectv2.topcoder-dev.com
  skip_cleanup: true
  local_dir: dist
  on:
    branch: [ "dev", "feature/deep-links"]
- provider: s3
  cache_control: private, no-store, no-cache, must-revalidate, max-age=0
  detect_encoding: true
  access_key_id: $QA_AWS_KEY
  secret_access_key: $QA_AWS_SECRET
  bucket: connectv2.topcoder-qa.com
  skip_cleanup: true
  local_dir: dist
  on:
    branch: qa
- provider: s3
  cache_control: private, no-store, no-cache, must-revalidate, max-age=0
  detect_encoding: true
  access_key_id: $MASTER_AWS_KEY
  secret_access_key: $MASTER_AWS_SECRET
  bucket: connectv2.topcoder.com
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
- provider: s3
  cache_control: private, no-store, no-cache, must-revalidate, max-age=0
  detect_encoding: true
  access_key_id: $TEST_AWS_KEY
  secret_access_key: $TEST_AWS_SECRET
  bucket: connect-testa.topcoder-dev.com
  region: us-west-2
  skip_cleanup: true
  local_dir: dist
  on:
    branch: test/deploy-test
env:
  matrix:
  - CXX=g++-4.8
  global:
  - secure: VZGhD2GYgEq18ECi87iPdp/PjRpYsGtvoXNn5qs2xSdmVUI7HbClGFQXftiwUWOlTJ+4TwiEsbykVB6VK2ePfM2rRr222tPKaJ6q7az8wkdJPaNo87/PTYZbnV1nOvs11GlLRJC/kYGpdDgShLhdO77lv5lLpL9fvengu7UVPjNTmHVwIiwYVOzASrNTNRd6gB/3Yf9QhnIQPPjIB6MApVqIwhUamyFEZnJV7sJa7z7hwCXujBkqsLoPDuJqWZYJjrWUz2g2DD1OzGqae9xO05RG5RwgC6ABGPMSt6+V/Q4xzRIDV+ogQXGg0aMWv4eNacdjG8GSHzBKVr0u5zUYiNmXIvrGf5tEo+3GdCx/RcWrJmB+bvJSY7H5bsr4auEKMv4u1u3vXyBtr86klUmqZvNZNZJpNt3cLUsrDsRgrtSEoYJ01bSLdYxuuWe++/ssDyYq0tkl+cf1/rk5NlmQOJPa9Vu1V5sMqgx3NKwhkL650HTwUOJhgvfmh5K0quwnQrc0idh4yMCyR4UX4yPGrzplYfarvce8yvOTjRmmgF4QWeAZl3a9myAI+Rp5I3ZV2dgjfVCaRbQKLdYW0eEnkGGhhap3yHYsdrudLtpRd+u/rJB6k8cJHHQvL3OkdSkbahQ4j0XvxRElJ7ucRJsP8SN9T1FmkvKb8fn8zHaex3s=
  - secure: PG2eUElqRRmuskRQAsFxHggyj7Ci2KQh82x/ke/QKPcL6VyCQRYCVuMmfFnmmqzdIzCXPGA7QN+g2p1TPufBunLjoszsaq4nSJs0OZyH6viUqQHGjnnzr2+hORuqPS0nKiKTYEjrB+iiVV//E4axtJD0DuqUJODPS8C5MqdLpClSn2TWySiINa5pGTlVn1QqbnxmabltVIgiZhiOtU2hqIRsSQD21GljM7lj9y3ZsXIYHhEgaEUY6s7nWVkTy0nsVByZshzf6mtoGh9eZLzxILQ50GsKAVJLUzanzBQO55u916nmIHmcMxPXNPkUpMwlG0AWSxzTHMMLOQbnVTcD0MWSyEtsYR/vpWu5kxN7RDVBDtFtyO1hYHP8ggW+mIFEaPgpHFTIb8tMZWQ0jGAM2AoMP3aN4XoL9IGYKNw9/LkV+7lLWEZtgcehIxg7Lwdp4hINoNQ4cfY937+2ThxiaiwAyB2Xvoi7ER4zXUZyiXdHqPFP4EV368QeQXjzGyHoDhXNNO9AzgQTWfk7iq3B7RPSP5uQLv7Z61AkyAK78F0f3jo529gp0fB7J84NCMkZtvJnN40u4DXfQP/zJVJHfaJ1nRiim5egNtdzoHHnTL1kQrJpp/+yaf7ZghCJpIYymEoy5Es6H8UCQJoDKHiXlWqZBxPsrJkFAvMxe3qmXTE=
  - secure: Q+cczazPHfMFPTh3EUYElozt+UkOMKC3tHlRbiBKVHkJpgxxH03Bqs+vgWc2XDo/6Ge9xFGOCT28CJf1Q4Gs7Dm0N0TlME5RlVrZjS78h+85K/ZwTSo4Bu70Wk1hm2wZ9EJtumrzoKEXy+L/8XSTzMIjkhkDqbjp9GZuYxrbQrJSPvYntWMNBP6hht1H/MtLlZVGtcRTFkOy/2u+hy1ELgvHSRAqWqLJfP+CdjtkryllGKWrZ1JXtiCuSEkp1jB9QVDLV1cNGVFqfWwPPU+DbhZNEN/H3jdztWmBVdXuIl9SZUBsq2//CEAUf4wX4mzzuGjl/Y8sXni39yTCpFdjWwywxWPFHbg+qog9gOOayaQ7vSeCuARn+mJqoVtGiLAQJWHiIa+QeXo6lABlXBBI3KohnFd7qi4v89P/fJrzRXd5wAnsstkSNJoVdC2+E8XPl95QHDOaVoDubxZMaexmUleXO68sczEZcs1zutkFEMudt0iS1HuTpTislY8bWQwyU9rW0VsWc0PrlDgQZBZuZUCAH8fx3QlIghGN9wUqM3x1JMW9fH389B6i8FmZrkxSwhGlg/zpAFEr6xg3mnuZvV/SDIy6URUwjWY/DKca0Gk2P8+KQEXR7627pFc4Os86LQhoO1oNFPVHDHvvn5MWdNcXqkMf9isTb24JzAzuFUs=
  - secure: FQN6bnwY2uIhV7IxF/JrvFXErefhox+yhKZ/97q2yB+l+k4032RSOsJl0MdX4Khi0DR8Dqex8nR0emMX245Yj+zcjkfn3MLuTR454xERQiYqZ4ULJqQAbkdHQ4XHHU2JQeD2gLbXHSsbu6EXXWPEsTpoW4xAwcI3O9S14kmbN172CCIi54Ac8RQ6Z3oJ3LKGnToyXov/cMXstV3PCXBMrZVLMDQP5UEvbP+Ze+HrAIx4OnF9CMlWfa0SRFltjmNA5Lkg9iL+LRcjZMa+2F1U/uuMLXO4KLkUK1YgVf5pY8LKDZUVajdlyoTsLVdffrAutKiEvwsBMq4FXgJzr5aFs+xdA4dcRYM8WzwzMo8Wk8sMtLoW8An0fzDDBYD+gP+k+iL+XdriGtPOi0u/wIDguglLehMtsKwnnawS8eQ6cwgSa4jW3NPcvJuTmVgQWUvAez71ZZ0KC/WQVBsUUerMDnpmSsnPpnekJDNFBJmzS7hLF/ERuDG2yZsu1/yXPC0bVHz09WDVR7GA5ajQpSXBREXmf080fdDE20zA6gFKHYPnQvP4J6aJwDJ/VX63B0idI1DXXMMTitjuebDff9tP7AWwv+M1gkCTof6x+eJ84Zd80B9TO7nFcYCXQQHVXt9BMpOoov2iPv5lEFykh4qAwy0Mqv5IYwuvSAq6A6oh1as=
  # $MASTER_AWS_KEY
  - secure: C3NYP6gj6w6cWGBQYrgT1tioSfaYpRzBf5PWVW2RG2pfzcWduB9x1GYWGhYWe3nSGKt9eao1JVTKph3HQW2oVS8U5GjwuT8opfC4k+xzrydiX9xplTC74gcigGTg3MIRuKPB8IhCNxvtKCllCTuVoVfVjScVB22zgwM6b3OArbSXFpBQEHjL3tcwTcjXy82s0u4wl4gIDvwbnZkUO01sCA+Yk7dYQfE+R0sSrozdexjkR/6ska++s+LzdNgGLUtDvKdf8VtF5z/htaqBWCIYNIrQEz6yClEEb7fW+4f7fK5KcGgCsocLPaUZPZc0mypsFiFxLLFdu+yBDNItXcEfKBuUhTSZV0z/l/dBrGLrY+rbjrr3YsQvnmco9JbUyMh6Or4JYuf2ofvw31SXuf9lrmUHaul7Yu+ibdfuoYJ9xTgZs1AKaGbyhhF+hxOM4YMkVB7byWacqiVE2G9RKqD02HxOL0UYnRZUisyt7oSXDBMEXvhzr2zfD43NgngSHhxpy6vzFCsGsXBEoYZD4DFrV6dym60kGmXd/24d6t8cXiRq+6xsWH7aU61fu8AppKAZJeMv/qHxxtM9lXJ1LaHKsiav/leTVcy1OXLPNNDOK20I99FEqVSNKvJ79uagR6xbcDnI4LRlw+uDKaY6AMSLIw9M5tWdAc6LNR9Wcyzop6E=
  # $MASTER_AWS_SECRET
  - secure: QTbD+n84Eg1QRZs7yjLl2yRdKmesr/yTTvSSX77xiKJB3kcI6UivJDoaWkIKq2WaxxA6ewf7UGdvGiM/q6PSpHmP9khNdxj3qXCn3OpUKZ+wVCz6JZ6JWWBBIBnKhTgFLz8O9jpxMRsXB0ZbF0k2JE6n/2qD96+rF0UmjfsJs7havOuHPNI4LwrRYSP8KzdbGRbcAUWesASTyq8nktv+kF93NomNaaRyyHBWCQMpEGS67B536IfFjypR919SIv+Qu4sqDATelQlSZWZm1jzupz3cAo8GNB6v1vYGNRMnM56R0rgDpOIqN6b6Y6hmHodSBMYp52sxFvcTuDDLuLvyGRQ/ErINmdcaXqgMh5Gl3tDwHezT5s32B+rOsSIkZF8fnrNB74dMpuKp7g2XCVfPeqlnEttY/uGbuQBe3be0g3kGtK9MFRw75X6oQxESaO2NvkCqPNZl1TacDv1s46bz3Y+en4gTmJ1UXKwmWf7fOekYozNBnOtcWQZqJ0g3d1DU1Pul4QSFuszL6y0uH5ohWDjk0mOERuFIQXKCrTVsMzUogeGp3Z7rDAynwFYGbJWgeoclbH2fQpbCLFSZxfvbYzzkpYbWD3eMLcpuKjSjTew8KEiYk2uYEjW9Kaj1wWkAkIGDAawbMGw5XVS/3a/scAcVMkyYb9VVy1wDAHudiRI=
  # $TEST_AWS_KEY
  - secure: OWWqJVAaY0JbcxxhUukj2DESSA103pdnHW2ItfePLbUshK2ITaDhot8pPznBw1EPboKKuwgevNnEvhSf8oUWlO8UZV+lgIldSaLkz01/v6AhnXTxOJWAjMuM/PkMXwnodMNa33l+fbCTs3213RNqUpOypTLGDYtyDeYNBgcEPYT3vOKHGECuXWweez71ZeAt/Fvis/Y9pilKQGzmClNz/pU5s1lalY3GBbydT6NpmbhgdXe5CbS/3VESiBmakdBlSIsPKP4FPCjTcRfh/rsvwxcHeYe/Xoe7tLTeD2cZdM56s4HogWGBvYPqijUq9kxtJ7DC2dhAUYpQPVKCNoZdq+J9b3oPPndI7ucXCPTwczyuZmgFm2GrEl+9o0YyX5ZsbjeqZYkmLL01WDzY+TI+RCSDgB5AHtcpLd/fX8RfDj6kmRDXe1T98AhqH3ZJqSEm2RmNZApkZguiivLv0M88j0KvePKB+HUEs72yUPR8E61FnNMwp1zhQsCEmDcN8NLxxxcNwJLAYZlF0s+CqzyqXxosIpZ5l8JptXZ1Z9+sDqqlDHHUNrNXqLbk5OXycfD7VBY+2Iv/OoOpyIy+rjz9a7Sr5ymqMwo+eUJpD3/PdueGBP9ORWYPztvcLC6s9UjfARju/hXdIyA9IdDI94gu8t50FtJhkfM9bwvtnrx5AME=
  # $TEST_AWS_SECRET
  - secure: xYUjFf7eeCfqY70vHUSacrymQFRLgV14g1IY8M4vg5hjpmkAWeP56tZM4QCEAeK6HePtrg0nxL/SGMx4vlpsXYiPg8iuO5PlbNBJTqOIdghHQN+ieVxEFbuF7rK17RA8tSiP3xwyY0OzVpwPeLAPdLaJBdH9cceUk7Ghw3pqrI3443HZRvF9cwhB5fhzvRqELscEPKe0PBJnBV41wcGmjz47s0LUVCuo17J8jpEi+ww7MzQJpN80p0+yLectjlqK6vfjgsIGbRF5X6zU+wdpFD4kWRToaEMEzJsaP7eCqddyrJB72lZ52DK4Bim5C0t4r5kqfIogRn7uUXaIftLowy2tUeiiPOfB0ON0QTqIZh8zr035stISfPx1YkOA0EjELcXu9JZVMDHKwsJdN7zOIEVZb5ZOVyd9AWGdxtxOTsWtYZ4wEtO24QKSp0i4EAaa70Las8clmXGRB7LdspB7LHA5Kp/9Zvfa4Dtr/wCImjtYubrP6pp/hG42+a+oRgH4rDUVBSUoKiqDbvQHTRdSS/21ldbvpNop+W2c6ayTRL16aRy3Fp+uEfv8weo0ScwZZeqDYNUpJY5jiW2xY35j6OWZFl4hW6Mxx7e1UrHi6/eaGVhJpZHwFsZx7sRzw87UrAP3SbIDZnViePwhxJfJk59OWlNP4i0bUmEO6bD3J60=
# enable once travis supports branch specific builds
# notifications:
#   slack:
#     secure: iVeMQ0kU5ydDtuVZkJtiO4ofjqiLNZBko5cbscqKbCO8hlsyozO6g9Pg90PqILEMcoPbiLDDNtBpLfL4GSdE0PfIiwMnbCDBnBaZ+dc/BqLMbJpAMxn7fnmK322b+/JCRGFDe+3xOEHnhgFgRubx0UFGb/6LVni0lN++k0rwV5gfzVw3G+rUT5ozSDoDMci+A8moMPKOKLswOGbOv/PF5OzV2rA8IQ5LTqLHXI19IpDZ0rZJZpOM3nmbbbF5/pLBgvseqKD/Fy/lOX0Cj6Z7oqOqZxXC2YI1cPkCCdam80FlH0tn2RqPyn6lJxQkF5DQNAtSut6NvhlS1vUNGF5EQ3RdtAQ3Zf5MbLKjmBcLWizy8mJtlV9HhrO2gHGyS4oCfIVqJWmRECPZKOVk4Bid9A2BAnJnzu49JUL+FRMW66P+pdwkPF4GK1yEl+GzR3QGiX1b+xHR1aNgD+xmmnKSNGx6nWNJIEYLY6QtNSiLIKndheRbyNnY7YoseORNyrPANTLPlgxgS5yY5B9G2Bi5rYbDmqI/bSD3pY2Bg+a4KLpq0/SR5wAN6sn8b6WpKBKv/O/3auat0GckeouK+Arvl4ow+k92DzOBpKkwj286Z5tNd/hHQY67QRf1YJn+laKf7kK1uVRzIKTZbHRBdDwS5UcaQHYImTqoLtpzR0HtvUo=
#   on_failure: change
